using System.Collections.ObjectModel;

namespace IsleBar.Core.Localization;

/// <summary>
/// Supported languages and strings. 10 languages = the same list as Slack (decision 09-29). Chinese in both Simplified and Traditional.
/// The strings are carried over as-is from <c>_T</c> in <c>reference/claude_bar.py</c>.
/// </summary>
public static class LanguageCatalog
{
    /// <summary>Language code and the language's name in itself. Shown in this order in the settings menu.</summary>
    public static readonly IReadOnlyList<LanguageInfo> Languages =
    [
        new("en", "English"),
        new("zh", "简体中文"),
        new("zht", "繁體中文"),
        new("fr", "Français"),
        new("de", "Deutsch"),
        new("it", "Italiano"),
        new("ja", "日本語"),
        new("ko", "한국어"),
        new("pt", "Português"),
        new("es", "Español"),
    ];

    /// <summary>Auto (the value stored when "Auto" is chosen in settings).</summary>
    public const string Auto = "auto";

    /// <summary>Language used when a string cannot be found.</summary>
    public const string Fallback = "en";

    private static readonly ReadOnlyDictionary<string, LanguageStrings> Table = new(BuildTable());

    public static IReadOnlyCollection<string> Codes => Table.Keys;

    public static bool IsKnown(string? code) => code is not null && Table.ContainsKey(code);

    /// <summary>Strings for a language code. Unknown codes get English.</summary>
    public static LanguageStrings For(string? code)
        => code is not null && Table.TryGetValue(code, out var strings) ? strings : Table[Fallback];

    private static Dictionary<string, LanguageStrings> BuildTable() => new(StringComparer.Ordinal)
    {
        ["en"] = new LanguageStrings
        {
            Finishing = "Finishing", Options = "Launch options", Settings = "Settings",
            Quit = "Close search bar", LaunchFail = "Launch failed: {}",
            NoSdk = "Everything SDK (Everything64.dll) not found", EsOff = "Everything is not running",
            EsFail = "File search failed", NoResult = "No results", Done = "Done", Fail = "Failed",
            Prep = "Preparing", MinSec = "{m}m {s:02d}s", Sec = "{s}s",
            Lang = "Language", Auto = "Auto", Folder = "Working folder", FolderChange = "Change",
            FolderHome = "Home", Files = "File search (Everything)",
            Session = new("Session", ["New", "Recent", "Pick"]),
            Model = new("Model", ["Default", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("Effort", ["Default", "Low", "Medium", "High", "Max"]),
            Perm = new("Permissions", ["Bypass", "Auto", "Plan", "Ask"]),
            Rc = "Remote control",
            Agent = "Agent",
            Dismiss = "Dismiss",
            WebEngine = "Web search engine",
            TabOrder = "Tab order",
            WebSearch = "Web search",
            Timer = "Timer",
            // ---- System notices (09-30) ----
            NoticeCharging = "Charging · {p}%",
            NoticeOnBattery = "On battery · {p}%",
            NoticeBatteryLevel = "Battery {p}%",
            NoticeAboutMin = "about {m} min",
            NoticeAboutHourMin = "about {h} h {m} min",
            NoticeConnected = "{} · Connected",
            NoticeDisconnected = "{} · Disconnected",
            NoticeOffline = "No internet",
            NoticeOnline = "Back online",
            NoticeFocus = "Focus session",
            NoticeCopied = "Copied · {}",
            NoticeCopiedImage = "Image copied",
            NoticeCopiedFile = "File copied",
            NoticeCopiedFiles = "{n} files copied",
            NoticeCpu = "CPU {p}%",
            NoticeMemory = "Memory {p}%",
            NoticeEventSoon = "In {m} min",
            NoticeEventNow = "Now",
            NoticeMicInUse = "Microphone in use",
            NoticeCameraInUse = "Camera in use",
            NotifySection = "Island notices",
            NotifyPower = "Charging & battery",
            NotifyBluetooth = "Bluetooth devices",
            NotifyNetwork = "Internet connection",
            NotifyFocus = "Focus sessions",
            NotifyClipboard = "Copied to clipboard",
            NotifyLoad = "High CPU & memory",
            NotifyPrivacy = "Microphone & camera in use",
            NotifyToasts = "Windows notifications (reads every notification)",
            HideToastBanners = "Show Windows notifications only on the bar (hide Windows pop-ups)",

            CrashReports = "Send crash reports (the error, app and Windows version, basic device info — no files, titles or questions)",
            CheckUpdates = "Check for updates once a day",
            UpdateAvailable = "Update available — click to install",
            UpdateMenu = "Update now",
            AllNotifications = "All notifications",
            ResetsAt = "resets at {}",
            UsageLimit = "{a} usage limit",
            UsageHigh = "{a} usage {p}%",
            AgentStopped = "{a} stopped",
            StopLogin = "sign in again",
            StopBilling = "check your plan",
            StopBusy = "servers busy, try again",
            StopError = "stopped by an error",
            MuteChimeFullscreen = "Mute the chime in full screen (games, videos)",
            UpdateFailed = "Update failed — click to download it yourself",
            ConnectAgents = "Connect Claude Code / Codex (working · needs you · done on the bar)",
            ConnectAgentsCard = "Show what Claude Code / Codex is doing here — click to connect",
            CalendarIcs = "Calendar (ICS link)",
            CalendarIcsHint = "Paste your calendar's secret iCal address — leave empty to turn off",
            DropCommand = "Drop command",
            DropCommandHint = "Files dropped on the bar are passed to this command (e.g. \"pythonw.exe\" \"C:\\send.py\"). Empty = attach to the prompt",
            DropToAttach = "Attach to prompt",
            ReplaceTimerAsk = "Replace timer? ↵ / Esc",
            StyleSection = "Appearance",
            StyleGlass = "Glass edge (dark taskbar)",
            Pomodoro = "Pomodoro",
            Stopwatch = "Stopwatch",
            Focus = "Focus",
            Break = "Break",
            Minutes = "{0} min",
            PomodoroMinutes = "Pomodoro (focus / break / long break, min)",
            QuickTimersLabel = "Quick timers in the right-click menu (min, comma-separated)",
            NativeSearchBox = "Hide the real search box (native)",
            AudioBars = "Music bars follow the sound",
            Working = "working",
            NeedsAnswer = "needs you",
            AgentDone = "done",
        },
        ["ko"] = new LanguageStrings
        {
            Finishing = "마무리 중", Options = "실행 옵션", Settings = "설정",
            Quit = "검색창 끄기", LaunchFail = "실행 실패: {}",
            NoSdk = "Everything SDK(Everything64.dll)가 없어요", EsOff = "Everything이 꺼져 있어요",
            EsFail = "파일 검색 실패", NoResult = "결과 없음", Done = "완료", Fail = "실패",
            Prep = "준비 중", MinSec = "{m}분 {s:02d}초", Sec = "{s}초",
            Lang = "언어", Auto = "자동", Folder = "작업 폴더", FolderChange = "바꾸기",
            FolderHome = "홈으로", Files = "파일 검색 (Everything)",
            Session = new("대화", ["새로", "최근", "목록"]),
            Model = new("모델", ["기본", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("생각 강도", ["기본", "낮음", "보통", "높음", "최대"]),
            Perm = new("권한", ["모두 허용", "자동", "계획", "묻기"]),
            Rc = "원격 조종",
            Agent = "에이전트",
            Dismiss = "지우기",
            WebEngine = "웹 검색 엔진",
            TabOrder = "Tab 순서",
            WebSearch = "웹 검색",
            Timer = "타이머",
            // ---- System notices (09-30) ----
            NoticeCharging = "충전 중 · {p}%",
            NoticeOnBattery = "배터리 · {p}%",
            NoticeBatteryLevel = "배터리 {p}%",
            NoticeAboutMin = "약 {m}분",
            NoticeAboutHourMin = "약 {h}시간 {m}분",
            NoticeConnected = "{} · 연결됨",
            NoticeDisconnected = "{} · 연결 끊김",
            NoticeOffline = "인터넷 끊김",
            NoticeOnline = "다시 연결됨",
            NoticeFocus = "집중 세션",
            NoticeCopied = "복사됨 · {}",
            NoticeCopiedImage = "이미지 복사됨",
            NoticeCopiedFile = "파일 복사됨",
            NoticeCopiedFiles = "파일 {n}개 복사됨",
            NoticeCpu = "CPU {p}%",
            NoticeMemory = "메모리 {p}%",
            NoticeEventSoon = "{m}분 후",
            NoticeEventNow = "지금",
            NoticeMicInUse = "마이크 사용 중",
            NoticeCameraInUse = "카메라 사용 중",
            NotifySection = "섬 알림",
            NotifyPower = "충전·배터리",
            NotifyBluetooth = "블루투스 기기",
            NotifyNetwork = "인터넷 연결",
            NotifyFocus = "집중 세션",
            NotifyClipboard = "클립보드 복사",
            NotifyLoad = "CPU·메모리 과부하",
            NotifyPrivacy = "마이크·카메라 사용",
            NotifyToasts = "Windows 알림 끌어오기(모든 알림 내용을 읽어요)",
            HideToastBanners = "Windows 알림은 바에서만 보기(Windows 팝업 숨김)",

            CrashReports = "오류 보고 보내기 (오류 내용·앱/Windows 버전·기본 기기 정보만 — 파일·창 제목·질문은 보내지 않음)",
            CheckUpdates = "하루에 한 번 업데이트 확인",
            UpdateAvailable = "업데이트가 있어요 — 눌러서 설치",
            UpdateMenu = "지금 업데이트",
            AllNotifications = "알림 모두 보기",
            ResetsAt = "{} 초기화",
            UsageLimit = "{a} 사용 한도 도달",
            UsageHigh = "{a} 사용량 {p}%",
            AgentStopped = "{a} 작업 멈춤",
            StopLogin = "다시 로그인 필요",
            StopBilling = "요금제·결제 확인 필요",
            StopBusy = "서버 혼잡 · 잠시 후 다시",
            StopError = "오류로 중단됨",
            MuteChimeFullscreen = "전체 화면(게임·영상)일 때 알림음 끄기",
            UpdateFailed = "업데이트 실패 — 눌러서 직접 받기",
            ConnectAgents = "Claude Code / Codex 연결 (작업 중 · 확인 필요 · 완료를 바에 표시)",
            ConnectAgentsCard = "Claude Code / Codex 상태를 여기서 보기 — 눌러서 연결",
            CalendarIcs = "일정 (ICS 링크)",
            CalendarIcsHint = "캘린더의 비공개 iCal 주소를 붙여 넣으세요 — 비우면 꺼져요",
            DropCommand = "끌어다 놓기 명령",
            DropCommandHint = "알약에 놓은 파일을 이 명령에 넘겨요(예: \"pythonw.exe\" \"C:\\send.py\"). 비우면 프롬프트에 첨부",
            DropToAttach = "프롬프트에 첨부",
            ReplaceTimerAsk = "타이머 바꿀까요? ↵ / Esc",
            AdvancedSection = "고급",
            StyleSection = "모양",
            StyleGlass = "빛 테두리(어두운 작업표시줄)",
            Pomodoro = "뽀모도로",
            Stopwatch = "스톱워치",
            Focus = "집중",
            Break = "휴식",
            Minutes = "{0}분",
            PomodoroMinutes = "뽀모도로 (집중 / 휴식 / 긴 휴식, 분)",
            QuickTimersLabel = "우클릭 메뉴 빠른 타이머 (분, 쉼표로)",
            NativeSearchBox = "진짜 검색창 숨기기(네이티브)",
            AudioBars = "음악 막대를 실제 소리에 맞추기",
            Working = "작업 중",
            NeedsAnswer = "확인 필요",
            AgentDone = "완료",
        },
        ["ja"] = new LanguageStrings
        {
            Finishing = "仕上げ中", Options = "起動オプション", Settings = "設定",
            Quit = "検索バーを閉じる", LaunchFail = "起動に失敗しました: {}",
            NoSdk = "Everything SDK (Everything64.dll) が見つかりません", EsOff = "Everything が起動していません",
            EsFail = "ファイル検索に失敗しました", NoResult = "結果なし", Done = "完了", Fail = "失敗",
            Prep = "準備中", MinSec = "{m}分{s:02d}秒", Sec = "{s}秒",
            Lang = "言語", Auto = "自動", Folder = "作業フォルダー", FolderChange = "変更",
            FolderHome = "ホーム", Files = "ファイル検索 (Everything)",
            Session = new("会話", ["新規", "最近", "一覧"]),
            Model = new("モデル", ["既定", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("思考の強さ", ["既定", "低", "中", "高", "最大"]),
            Perm = new("権限", ["すべて許可", "自動", "計画", "確認"]),
            Rc = "リモート操作",
            Agent = "エージェント",
            Dismiss = "消す",
            WebEngine = "ウェブ検索エンジン",
            TabOrder = "Tab の順番",
            WebSearch = "ウェブ検索",
            Timer = "タイマー",
            // ---- System notices (09-30) ----
            NoticeCharging = "充電中 · {p}%",
            NoticeOnBattery = "バッテリー · {p}%",
            NoticeBatteryLevel = "バッテリー {p}%",
            NoticeAboutMin = "約{m}分",
            NoticeAboutHourMin = "約{h}時間{m}分",
            NoticeConnected = "{} · 接続済み",
            NoticeDisconnected = "{} · 切断",
            NoticeOffline = "インターネット切断",
            NoticeOnline = "再接続しました",
            NoticeFocus = "集中セッション",
            NoticeCopied = "コピーしました · {}",
            NoticeCopiedImage = "画像をコピーしました",
            NoticeCopiedFile = "ファイルをコピーしました",
            NoticeCopiedFiles = "{n}個のファイルをコピーしました",
            NoticeCpu = "CPU {p}%",
            NoticeMemory = "メモリ {p}%",
            NoticeEventSoon = "{m}分後",
            NoticeEventNow = "今",
            NoticeMicInUse = "マイク使用中",
            NoticeCameraInUse = "カメラ使用中",
            NotifySection = "アイランド通知",
            NotifyPower = "充電・バッテリー",
            NotifyBluetooth = "Bluetooth デバイス",
            NotifyNetwork = "インターネット接続",
            NotifyFocus = "集中セッション",
            NotifyClipboard = "クリップボードへのコピー",
            NotifyLoad = "CPU・メモリの高負荷",
            NotifyPrivacy = "マイク・カメラの使用",
            NotifyToasts = "Windows の通知(すべての通知内容を読みます)",
            HideToastBanners = "Windows の通知をバーだけに表示(Windows のポップアップを隠す)",

            CrashReports = "クラッシュレポートを送信(エラー・アプリと Windows のバージョン・基本的な機器情報のみ — ファイル・タイトル・質問は送りません)",
            CheckUpdates = "1日1回アップデートを確認",
            UpdateAvailable = "アップデートがあります — クリックしてインストール",
            UpdateMenu = "今すぐアップデート",
            AllNotifications = "すべての通知",
            ResetsAt = "{} にリセット",
            UsageLimit = "{a} の利用上限",
            UsageHigh = "{a} 使用量 {p}%",
            AgentStopped = "{a} が停止",
            StopLogin = "再ログインが必要",
            StopBilling = "プランを確認",
            StopBusy = "サーバー混雑・再試行",
            StopError = "エラーで停止",
            MuteChimeFullscreen = "全画面（ゲーム・動画）のとき通知音を鳴らさない",
            UpdateFailed = "アップデートに失敗 — クリックして手動でダウンロード",
            ConnectAgents = "Claude Code / Codex と接続(作業中・確認待ち・完了をバーに表示)",
            ConnectAgentsCard = "Claude Code / Codex の状態をここに表示 — クリックして接続",
            CalendarIcs = "カレンダー (ICS リンク)",
            CalendarIcsHint = "カレンダーの非公開 iCal アドレスを貼り付け — 空欄でオフ",
            DropCommand = "ドロップ時のコマンド",
            AdvancedSection = "詳細設定",
            DropCommandHint = "バーにドロップしたファイルをこのコマンドに渡します(例: \"pythonw.exe\" \"C:\\send.py\")。空欄で既定",
            DropToAttach = "プロンプトに添付",
            ReplaceTimerAsk = "置き換え？ ↵ / Esc",
            StyleSection = "外観",
            StyleGlass = "ガラスの縁(暗いタスクバー)",
            Pomodoro = "ポモドーロ",
            Stopwatch = "ストップウォッチ",
            Focus = "集中",
            Break = "休憩",
            Minutes = "{0}分",
            PomodoroMinutes = "ポモドーロ (集中 / 休憩 / 長い休憩、分)",
            QuickTimersLabel = "右クリックメニューのクイックタイマー (分、カンマ区切り)",
            NativeSearchBox = "本来の検索ボックスを隠す(ネイティブ)",
            AudioBars = "音楽バーを実際の音に合わせる",
            Working = "作業中",
            NeedsAnswer = "確認待ち",
            AgentDone = "完了",
        },
        ["zh"] = new LanguageStrings
        {
            Finishing = "收尾中", Options = "启动选项", Settings = "设置",
            Quit = "关闭搜索栏", LaunchFail = "启动失败: {}",
            NoSdk = "未找到 Everything SDK (Everything64.dll)", EsOff = "Everything 未运行",
            EsFail = "文件搜索失败", NoResult = "无结果", Done = "完成", Fail = "失败",
            Prep = "准备中", MinSec = "{m}分{s:02d}秒", Sec = "{s}秒",
            Lang = "语言", Auto = "自动", Folder = "工作文件夹", FolderChange = "更改",
            FolderHome = "主目录", Files = "文件搜索 (Everything)",
            Session = new("对话", ["新建", "最近", "选择"]),
            Model = new("模型", ["默认", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("思考强度", ["默认", "低", "中", "高", "最高"]),
            Perm = new("权限", ["全部允许", "自动", "计划", "询问"]),
            Rc = "远程控制",
            Agent = "代理",
            Dismiss = "移除",
            WebEngine = "网页搜索引擎",
            TabOrder = "Tab 顺序",
            WebSearch = "网页搜索",
            Timer = "计时器",
            // ---- System notices (09-30) ----
            NoticeCharging = "充电中 · {p}%",
            NoticeOnBattery = "使用电池 · {p}%",
            NoticeBatteryLevel = "电量 {p}%",
            NoticeAboutMin = "约 {m} 分钟",
            NoticeAboutHourMin = "约 {h} 小时 {m} 分钟",
            NoticeConnected = "{} · 已连接",
            NoticeDisconnected = "{} · 已断开",
            NoticeOffline = "网络已断开",
            NoticeOnline = "已重新连接",
            NoticeFocus = "专注时段",
            NoticeCopied = "已复制 · {}",
            NoticeCopiedImage = "已复制图片",
            NoticeCopiedFile = "已复制文件",
            NoticeCopiedFiles = "已复制 {n} 个文件",
            NoticeCpu = "CPU {p}%",
            NoticeMemory = "内存 {p}%",
            NoticeEventSoon = "{m} 分钟后",
            NoticeEventNow = "现在",
            NoticeMicInUse = "麦克风使用中",
            NoticeCameraInUse = "摄像头使用中",
            NotifySection = "岛通知",
            NotifyPower = "充电与电池",
            NotifyBluetooth = "蓝牙设备",
            NotifyNetwork = "网络连接",
            NotifyFocus = "专注时段",
            NotifyClipboard = "剪贴板复制",
            NotifyLoad = "CPU 与内存占用过高",
            NotifyPrivacy = "麦克风与摄像头使用",
            NotifyToasts = "Windows 通知(会读取所有通知内容)",
            HideToastBanners = "Windows 通知只在栏中显示(隐藏 Windows 弹窗)",

            CrashReports = "发送崩溃报告(仅错误、应用与 Windows 版本及基本设备信息 — 不含文件、标题或提问)",
            CheckUpdates = "每天检查一次更新",
            UpdateAvailable = "有可用更新 — 点击安装",
            UpdateMenu = "立即更新",
            AllNotifications = "查看全部通知",
            ResetsAt = "{} 重置",
            UsageLimit = "{a} 用量已达上限",
            UsageHigh = "{a} 用量 {p}%",
            AgentStopped = "{a} 已停止",
            StopLogin = "需要重新登录",
            StopBilling = "请检查套餐",
            StopBusy = "服务器繁忙，请重试",
            StopError = "因错误中止",
            MuteChimeFullscreen = "全屏（游戏、视频）时静音提示音",
            UpdateFailed = "更新失败 — 点击手动下载",
            ConnectAgents = "连接 Claude Code / Codex(在栏上显示工作中 · 待确认 · 完成)",
            ConnectAgentsCard = "在这里查看 Claude Code / Codex 的状态 — 点击连接",
            CalendarIcs = "日历 (ICS 链接)",
            CalendarIcsHint = "粘贴日历的私密 iCal 地址 — 留空即关闭",
            DropCommand = "拖放命令",
            AdvancedSection = "高级",
            DropCommandHint = "拖到栏上的文件会交给此命令(例如 \"pythonw.exe\" \"C:\\send.py\")。留空使用默认",
            DropToAttach = "附加到提示",
            ReplaceTimerAsk = "替换计时器？↵ / Esc",
            StyleSection = "外观",
            StyleGlass = "玻璃边缘(深色任务栏)",
            Pomodoro = "番茄钟",
            Stopwatch = "秒表",
            Focus = "专注",
            Break = "休息",
            Minutes = "{0} 分钟",
            PomodoroMinutes = "番茄钟(专注 / 休息 / 长休息,分钟)",
            QuickTimersLabel = "右键菜单快速计时器(分钟,逗号分隔)",
            NativeSearchBox = "隐藏系统搜索框(原生)",
            AudioBars = "音乐条跟随实际声音",
            Working = "工作中",
            NeedsAnswer = "待确认",
            AgentDone = "完成",
        },
        ["zht"] = new LanguageStrings
        {
            Finishing = "收尾中", Options = "啟動選項", Settings = "設定",
            Quit = "關閉搜尋列", LaunchFail = "啟動失敗：{}",
            NoSdk = "找不到 Everything SDK (Everything64.dll)", EsOff = "Everything 未執行",
            EsFail = "檔案搜尋失敗", NoResult = "沒有結果", Done = "完成", Fail = "失敗",
            Prep = "準備中", MinSec = "{m}分{s:02d}秒", Sec = "{s}秒",
            Lang = "語言", Auto = "自動", Folder = "工作資料夾", FolderChange = "變更",
            FolderHome = "主目錄", Files = "檔案搜尋 (Everything)",
            Session = new("對話", ["新增", "最近", "選擇"]),
            Model = new("模型", ["預設", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("思考強度", ["預設", "低", "中", "高", "最高"]),
            Perm = new("權限", ["全部允許", "自動", "計畫", "詢問"]),
            Rc = "遠端控制",
            Agent = "代理",
            Dismiss = "移除",
            WebEngine = "網頁搜尋引擎",
            TabOrder = "Tab 順序",
            WebSearch = "網頁搜尋",
            Timer = "計時器",
            // ---- System notices (09-30) ----
            NoticeCharging = "充電中 · {p}%",
            NoticeOnBattery = "使用電池 · {p}%",
            NoticeBatteryLevel = "電量 {p}%",
            NoticeAboutMin = "約 {m} 分鐘",
            NoticeAboutHourMin = "約 {h} 小時 {m} 分鐘",
            NoticeConnected = "{} · 已連線",
            NoticeDisconnected = "{} · 已中斷連線",
            NoticeOffline = "網路已中斷",
            NoticeOnline = "已重新連線",
            NoticeFocus = "專注工作階段",
            NoticeCopied = "已複製 · {}",
            NoticeCopiedImage = "已複製圖片",
            NoticeCopiedFile = "已複製檔案",
            NoticeCopiedFiles = "已複製 {n} 個檔案",
            NoticeCpu = "CPU {p}%",
            NoticeMemory = "記憶體 {p}%",
            NoticeEventSoon = "{m} 分鐘後",
            NoticeEventNow = "現在",
            NoticeMicInUse = "麥克風使用中",
            NoticeCameraInUse = "相機使用中",
            NotifySection = "島通知",
            NotifyPower = "充電與電池",
            NotifyBluetooth = "藍牙裝置",
            NotifyNetwork = "網路連線",
            NotifyFocus = "專注工作階段",
            NotifyClipboard = "剪貼簿複製",
            NotifyLoad = "CPU 與記憶體負載過高",
            NotifyPrivacy = "麥克風與相機使用",
            NotifyToasts = "Windows 通知(會讀取所有通知內容)",
            HideToastBanners = "Windows 通知只在列中顯示(隱藏 Windows 彈出視窗)",

            CrashReports = "傳送當機報告(僅錯誤、應用程式與 Windows 版本及基本裝置資訊 — 不含檔案、標題或提問)",
            CheckUpdates = "每天檢查一次更新",
            UpdateAvailable = "有可用的更新 — 按一下安裝",
            UpdateMenu = "立即更新",
            AllNotifications = "查看所有通知",
            ResetsAt = "{} 重置",
            UsageLimit = "{a} 用量已達上限",
            UsageHigh = "{a} 用量 {p}%",
            AgentStopped = "{a} 已停止",
            StopLogin = "需要重新登入",
            StopBilling = "請檢查方案",
            StopBusy = "伺服器忙碌，請重試",
            StopError = "因錯誤中止",
            MuteChimeFullscreen = "全螢幕（遊戲、影片）時靜音提示音",
            UpdateFailed = "更新失敗 — 按一下手動下載",
            ConnectAgents = "連接 Claude Code / Codex(在列上顯示工作中 · 待確認 · 完成)",
            ConnectAgentsCard = "在這裡查看 Claude Code / Codex 的狀態 — 按一下連接",
            CalendarIcs = "行事曆 (ICS 連結)",
            CalendarIcsHint = "貼上行事曆的私人 iCal 網址 — 留空即關閉",
            DropCommand = "拖放命令",
            AdvancedSection = "進階",
            DropCommandHint = "拖到列上的檔案會交給此命令(例如 \"pythonw.exe\" \"C:\\send.py\")。留空使用預設",
            DropToAttach = "附加到提示",
            ReplaceTimerAsk = "取代計時器？↵ / Esc",
            StyleSection = "外觀",
            StyleGlass = "玻璃邊緣(深色工作列)",
            Pomodoro = "番茄鐘",
            Stopwatch = "碼錶",
            Focus = "專注",
            Break = "休息",
            Minutes = "{0} 分鐘",
            PomodoroMinutes = "番茄鐘(專注 / 休息 / 長休息,分鐘)",
            QuickTimersLabel = "右鍵選單快速計時器(分鐘,逗號分隔)",
            NativeSearchBox = "隱藏系統搜尋方塊(原生)",
            AudioBars = "音樂條跟隨實際聲音",
            Working = "工作中",
            NeedsAnswer = "待確認",
            AgentDone = "完成",
        },
        ["fr"] = new LanguageStrings
        {
            Finishing = "Finalisation", Options = "Options de lancement", Settings = "Paramètres",
            Quit = "Fermer la barre", LaunchFail = "Échec du lancement : {}",
            NoSdk = "Everything SDK (Everything64.dll) introuvable", EsOff = "Everything n'est pas lancé",
            EsFail = "Échec de la recherche", NoResult = "Aucun résultat", Done = "Terminé", Fail = "Échec",
            Prep = "Préparation", MinSec = "{m} min {s:02d} s", Sec = "{s} s",
            Lang = "Langue", Auto = "Automatique", Folder = "Dossier de travail", FolderChange = "Modifier",
            FolderHome = "Accueil", Files = "Recherche de fichiers (Everything)",
            Session = new("Session", ["Nouvelle", "Récente", "Choisir"]),
            Model = new("Modèle", ["Défaut", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("Effort", ["Défaut", "Faible", "Moyen", "Élevé", "Max"]),
            Perm = new("Autorisations", ["Ignorer", "Auto", "Plan", "Demander"]),
            Rc = "Contrôle à distance",
            Agent = "Agent",
            Dismiss = "Retirer",
            WebEngine = "Moteur de recherche web",
            TabOrder = "Ordre de Tab",
            WebSearch = "Recherche web",
            Timer = "Minuteur",
            // ---- System notices (09-30) ----
            NoticeCharging = "En charge · {p} %",
            NoticeOnBattery = "Sur batterie · {p} %",
            NoticeBatteryLevel = "Batterie {p} %",
            NoticeAboutMin = "env. {m} min",
            NoticeAboutHourMin = "env. {h} h {m} min",
            NoticeConnected = "{} · Connecté",
            NoticeDisconnected = "{} · Déconnecté",
            NoticeOffline = "Pas d'Internet",
            NoticeOnline = "De nouveau connecté",
            NoticeFocus = "Session de concentration",
            NoticeCopied = "Copié · {}",
            NoticeCopiedImage = "Image copiée",
            NoticeCopiedFile = "Fichier copié",
            NoticeCopiedFiles = "{n} fichiers copiés",
            NoticeCpu = "CPU {p} %",
            NoticeMemory = "Mémoire {p} %",
            NoticeEventSoon = "Dans {m} min",
            NoticeEventNow = "Maintenant",
            NoticeMicInUse = "Micro utilisé",
            NoticeCameraInUse = "Caméra utilisée",
            NotifySection = "Notifications de l'îlot",
            NotifyPower = "Charge et batterie",
            NotifyBluetooth = "Appareils Bluetooth",
            NotifyNetwork = "Connexion Internet",
            NotifyFocus = "Sessions de concentration",
            NotifyClipboard = "Copies dans le presse-papiers",
            NotifyLoad = "Processeur et mémoire saturés",
            NotifyPrivacy = "Micro et caméra utilisés",
            NotifyToasts = "Notifications Windows (lit toutes les notifications)",
            HideToastBanners = "Notifications Windows uniquement sur la barre (masquer les fenêtres Windows)",

            CrashReports = "Envoyer les rapports de plantage (erreur, versions de l’app et de Windows, infos de base sur l’appareil — ni fichiers, ni titres, ni questions)",
            CheckUpdates = "Rechercher les mises à jour une fois par jour",
            UpdateAvailable = "Mise à jour disponible — cliquez pour installer",
            UpdateMenu = "Mettre à jour maintenant",
            AllNotifications = "Toutes les notifications",
            ResetsAt = "réinitialisée à {}",
            UsageLimit = "Limite d'utilisation {a}",
            UsageHigh = "Utilisation {a} {p} %",
            AgentStopped = "{a} s'est arrêté",
            StopLogin = "reconnexion requise",
            StopBilling = "vérifiez votre forfait",
            StopBusy = "serveurs saturés, réessayez",
            StopError = "arrêté par une erreur",
            MuteChimeFullscreen = "Couper le son en plein écran (jeux, vidéos)",
            UpdateFailed = "Échec de la mise à jour — cliquez pour la télécharger",
            ConnectAgents = "Connecter Claude Code / Codex (en cours · attend · terminé sur la barre)",
            ConnectAgentsCard = "Voir ici ce que font Claude Code / Codex — cliquez pour connecter",
            CalendarIcs = "Agenda (lien ICS)",
            CalendarIcsHint = "Collez l'adresse iCal secrète de votre agenda — vide pour désactiver",
            DropCommand = "Commande de dépôt",
            AdvancedSection = "Avancé",
            DropCommandHint = "Les fichiers déposés sur la barre sont passés à cette commande (ex. \"pythonw.exe\" \"C:\\send.py\"). Vide = par défaut",
            DropToAttach = "Joindre au prompt",
            ReplaceTimerAsk = "Remplacer ? ↵ / Échap",
            StyleSection = "Apparence",
            StyleGlass = "Bord vitré (barre des tâches sombre)",
            Pomodoro = "Pomodoro",
            Stopwatch = "Chronomètre",
            Focus = "Concentration",
            Break = "Pause",
            Minutes = "{0} min",
            PomodoroMinutes = "Pomodoro (concentration / pause / longue pause, min)",
            QuickTimersLabel = "Minuteurs rapides du menu clic droit (min, séparés par des virgules)",
            NativeSearchBox = "Masquer la vraie zone de recherche (natif)",
            AudioBars = "Les barres suivent le son",
            Working = "en cours",
            NeedsAnswer = "attend",
            AgentDone = "terminé",
        },
        ["de"] = new LanguageStrings
        {
            Finishing = "Abschluss", Options = "Startoptionen", Settings = "Einstellungen",
            Quit = "Suchleiste schließen", LaunchFail = "Start fehlgeschlagen: {}",
            NoSdk = "Everything SDK (Everything64.dll) nicht gefunden", EsOff = "Everything läuft nicht",
            EsFail = "Dateisuche fehlgeschlagen", NoResult = "Keine Ergebnisse", Done = "Fertig", Fail = "Fehler",
            Prep = "Wird vorbereitet", MinSec = "{m} Min. {s:02d} s", Sec = "{s} s",
            Lang = "Sprache", Auto = "Automatisch", Folder = "Arbeitsordner", FolderChange = "Ändern",
            FolderHome = "Start", Files = "Dateisuche (Everything)",
            Session = new("Sitzung", ["Neu", "Zuletzt", "Auswählen"]),
            Model = new("Modell", ["Standard", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("Aufwand", ["Standard", "Niedrig", "Mittel", "Hoch", "Max."]),
            Perm = new("Berechtigungen", ["Umgehen", "Auto", "Plan", "Fragen"]),
            Rc = "Fernsteuerung",
            Agent = "Agent",
            Dismiss = "Entfernen",
            WebEngine = "Websuchmaschine",
            TabOrder = "Tab-Reihenfolge",
            WebSearch = "Websuche",
            Timer = "Timer",
            // ---- System notices (09-30) ----
            NoticeCharging = "Wird geladen · {p} %",
            NoticeOnBattery = "Akkubetrieb · {p} %",
            NoticeBatteryLevel = "Akku {p} %",
            NoticeAboutMin = "ca. {m} Min.",
            NoticeAboutHourMin = "ca. {h} Std. {m} Min.",
            NoticeConnected = "{} · Verbunden",
            NoticeDisconnected = "{} · Getrennt",
            NoticeOffline = "Kein Internet",
            NoticeOnline = "Wieder verbunden",
            NoticeFocus = "Fokussitzung",
            NoticeCopied = "Kopiert · {}",
            NoticeCopiedImage = "Bild kopiert",
            NoticeCopiedFile = "Datei kopiert",
            NoticeCopiedFiles = "{n} Dateien kopiert",
            NoticeCpu = "CPU {p} %",
            NoticeMemory = "Arbeitsspeicher {p} %",
            NoticeEventSoon = "In {m} Min.",
            NoticeEventNow = "Jetzt",
            NoticeMicInUse = "Mikrofon aktiv",
            NoticeCameraInUse = "Kamera aktiv",
            NotifySection = "Insel-Hinweise",
            NotifyPower = "Laden & Akku",
            NotifyBluetooth = "Bluetooth-Geräte",
            NotifyNetwork = "Internetverbindung",
            NotifyFocus = "Fokussitzungen",
            NotifyClipboard = "In Zwischenablage kopiert",
            NotifyLoad = "Hohe CPU- & Speicherlast",
            NotifyPrivacy = "Mikrofon & Kamera aktiv",
            NotifyToasts = "Windows-Benachrichtigungen (liest alle Benachrichtigungen)",
            HideToastBanners = "Windows-Benachrichtigungen nur in der Leiste (Windows-Pop-ups ausblenden)",

            CrashReports = "Absturzberichte senden (Fehler, App- und Windows-Version, Basisdaten zum Gerät – keine Dateien, Titel oder Fragen)",
            CheckUpdates = "Einmal täglich nach Updates suchen",
            UpdateAvailable = "Update verfügbar – zum Installieren klicken",
            UpdateMenu = "Jetzt aktualisieren",
            AllNotifications = "Alle Benachrichtigungen",
            ResetsAt = "zurückgesetzt um {}",
            UsageLimit = "{a}-Nutzungslimit erreicht",
            UsageHigh = "{a}-Nutzung {p} %",
            AgentStopped = "{a} wurde gestoppt",
            StopLogin = "erneut anmelden",
            StopBilling = "Tarif prüfen",
            StopBusy = "Server ausgelastet, erneut versuchen",
            StopError = "durch einen Fehler gestoppt",
            MuteChimeFullscreen = "Ton im Vollbild stummschalten (Spiele, Videos)",
            UpdateFailed = "Update fehlgeschlagen – zum manuellen Download klicken",
            ConnectAgents = "Claude Code / Codex verbinden (arbeitet · wartet · fertig in der Leiste)",
            ConnectAgentsCard = "Hier sehen, was Claude Code / Codex tun – zum Verbinden klicken",
            CalendarIcs = "Kalender (ICS-Link)",
            CalendarIcsHint = "Geheime iCal-Adresse des Kalenders einfügen — leer lassen zum Ausschalten",
            DropCommand = "Ablege-Befehl",
            AdvancedSection = "Erweitert",
            DropCommandHint = "Auf die Leiste gezogene Dateien werden an diesen Befehl übergeben (z. B. \"pythonw.exe\" \"C:\\send.py\"). Leer = Standard",
            DropToAttach = "An den Prompt anhängen",
            ReplaceTimerAsk = "Timer ersetzen? ↵ / Esc",
            StyleSection = "Darstellung",
            StyleGlass = "Glaskante (dunkle Taskleiste)",
            Pomodoro = "Pomodoro",
            Stopwatch = "Stoppuhr",
            Focus = "Fokus",
            Break = "Pause",
            Minutes = "{0} Min.",
            PomodoroMinutes = "Pomodoro (Fokus / Pause / lange Pause, Min.)",
            QuickTimersLabel = "Schnell-Timer im Rechtsklickmenü (Min., durch Kommas getrennt)",
            NativeSearchBox = "Echtes Suchfeld ausblenden (nativ)",
            AudioBars = "Balken folgen dem Klang",
            Working = "arbeitet",
            NeedsAnswer = "wartet",
            AgentDone = "fertig",
        },
        ["it"] = new LanguageStrings
        {
            Finishing = "Completamento", Options = "Opzioni di avvio", Settings = "Impostazioni",
            Quit = "Chiudi la barra", LaunchFail = "Avvio non riuscito: {}",
            NoSdk = "Everything SDK (Everything64.dll) non trovato", EsOff = "Everything non è in esecuzione",
            EsFail = "Ricerca file non riuscita", NoResult = "Nessun risultato", Done = "Fatto", Fail = "Errore",
            Prep = "Preparazione", MinSec = "{m} min {s:02d} s", Sec = "{s} s",
            Lang = "Lingua", Auto = "Automatica", Folder = "Cartella di lavoro", FolderChange = "Cambia",
            FolderHome = "Home", Files = "Ricerca file (Everything)",
            Session = new("Sessione", ["Nuova", "Recente", "Scegli"]),
            Model = new("Modello", ["Predef.", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("Impegno", ["Predef.", "Basso", "Medio", "Alto", "Max"]),
            Perm = new("Autorizzazioni", ["Ignora", "Auto", "Piano", "Chiedi"]),
            Rc = "Controllo remoto",
            Agent = "Agente",
            Dismiss = "Rimuovi",
            WebEngine = "Motore di ricerca web",
            TabOrder = "Ordine di Tab",
            WebSearch = "Ricerca web",
            Timer = "Timer",
            // ---- System notices (09-30) ----
            NoticeCharging = "In carica · {p}%",
            NoticeOnBattery = "A batteria · {p}%",
            NoticeBatteryLevel = "Batteria {p}%",
            NoticeAboutMin = "circa {m} min",
            NoticeAboutHourMin = "circa {h} h {m} min",
            NoticeConnected = "{} · Connesso",
            NoticeDisconnected = "{} · Disconnesso",
            NoticeOffline = "Nessuna connessione Internet",
            NoticeOnline = "Di nuovo connesso",
            NoticeFocus = "Sessione di concentrazione",
            NoticeCopied = "Copiato · {}",
            NoticeCopiedImage = "Immagine copiata",
            NoticeCopiedFile = "File copiato",
            NoticeCopiedFiles = "{n} file copiati",
            NoticeCpu = "CPU {p}%",
            NoticeMemory = "Memoria {p}%",
            NoticeEventSoon = "Tra {m} min",
            NoticeEventNow = "Ora",
            NoticeMicInUse = "Microfono in uso",
            NoticeCameraInUse = "Fotocamera in uso",
            NotifySection = "Avvisi dell'isola",
            NotifyPower = "Carica e batteria",
            NotifyBluetooth = "Dispositivi Bluetooth",
            NotifyNetwork = "Connessione Internet",
            NotifyFocus = "Sessioni di concentrazione",
            NotifyClipboard = "Copie negli appunti",
            NotifyLoad = "CPU e memoria sotto sforzo",
            NotifyPrivacy = "Microfono e fotocamera in uso",
            NotifyToasts = "Notifiche di Windows (legge tutte le notifiche)",
            HideToastBanners = "Notifiche di Windows solo sulla barra (nascondi i popup di Windows)",

            CrashReports = "Invia segnalazioni di arresto anomalo (errore, versione app e Windows, dati base del dispositivo — niente file, titoli o domande)",
            CheckUpdates = "Controlla gli aggiornamenti una volta al giorno",
            UpdateAvailable = "Aggiornamento disponibile — clicca per installarlo",
            UpdateMenu = "Aggiorna ora",
            AllNotifications = "Tutte le notifiche",
            ResetsAt = "si azzera alle {}",
            UsageLimit = "Limite di utilizzo di {a}",
            UsageHigh = "Utilizzo di {a} {p}%",
            AgentStopped = "{a} si è fermato",
            StopLogin = "accedi di nuovo",
            StopBilling = "controlla il piano",
            StopBusy = "server occupati, riprova",
            StopError = "interrotto da un errore",
            MuteChimeFullscreen = "Silenzia il suono a schermo intero (giochi, video)",
            UpdateFailed = "Aggiornamento non riuscito — clicca per scaricarlo",
            ConnectAgents = "Collega Claude Code / Codex (in corso · in attesa · fatto sulla barra)",
            ConnectAgentsCard = "Guarda qui cosa fanno Claude Code / Codex — clicca per collegare",
            CalendarIcs = "Calendario (link ICS)",
            CalendarIcsHint = "Incolla l'indirizzo iCal segreto del calendario — vuoto per disattivare",
            DropCommand = "Comando di rilascio",
            AdvancedSection = "Avanzate",
            DropCommandHint = "I file trascinati sulla barra vengono passati a questo comando (es. \"pythonw.exe\" \"C:\\send.py\"). Vuoto = predefinito",
            DropToAttach = "Allega al prompt",
            ReplaceTimerAsk = "Sostituire? ↵ / Esc",
            StyleSection = "Aspetto",
            StyleGlass = "Bordo in vetro (barra scura)",
            Pomodoro = "Pomodoro",
            Stopwatch = "Cronometro",
            Focus = "Concentrazione",
            Break = "Pausa",
            Minutes = "{0} min",
            PomodoroMinutes = "Pomodoro (concentrazione / pausa / pausa lunga, min)",
            QuickTimersLabel = "Timer rapidi nel menu del tasto destro (min, separati da virgole)",
            NativeSearchBox = "Nascondi la vera casella di ricerca (nativo)",
            AudioBars = "Le barre seguono il suono",
            Working = "in corso",
            NeedsAnswer = "in attesa",
            AgentDone = "fatto",
        },
        ["pt"] = new LanguageStrings
        {
            Finishing = "Finalizando", Options = "Opções de início", Settings = "Configurações",
            Quit = "Fechar a barra", LaunchFail = "Falha ao iniciar: {}",
            NoSdk = "Everything SDK (Everything64.dll) não encontrado", EsOff = "O Everything não está em execução",
            EsFail = "Falha na busca", NoResult = "Nenhum resultado", Done = "Concluído", Fail = "Falhou",
            Prep = "Preparando", MinSec = "{m} min {s:02d} s", Sec = "{s} s",
            Lang = "Idioma", Auto = "Automático", Folder = "Pasta de trabalho", FolderChange = "Alterar",
            FolderHome = "Início", Files = "Busca de arquivos (Everything)",
            Session = new("Sessão", ["Nova", "Recente", "Escolher"]),
            Model = new("Modelo", ["Padrão", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("Esforço", ["Padrão", "Baixo", "Médio", "Alto", "Máx."]),
            Perm = new("Permissões", ["Ignorar", "Auto", "Plano", "Perguntar"]),
            Rc = "Controle remoto",
            Agent = "Agente",
            Dismiss = "Remover",
            WebEngine = "Mecanismo de busca na web",
            TabOrder = "Ordem do Tab",
            WebSearch = "Busca na web",
            Timer = "Temporizador",
            // ---- System notices (09-30) ----
            NoticeCharging = "Carregando · {p}%",
            NoticeOnBattery = "Na bateria · {p}%",
            NoticeBatteryLevel = "Bateria {p}%",
            NoticeAboutMin = "cerca de {m} min",
            NoticeAboutHourMin = "cerca de {h} h {m} min",
            NoticeConnected = "{} · Conectado",
            NoticeDisconnected = "{} · Desconectado",
            NoticeOffline = "Sem internet",
            NoticeOnline = "Conectado novamente",
            NoticeFocus = "Sessão de foco",
            NoticeCopied = "Copiado · {}",
            NoticeCopiedImage = "Imagem copiada",
            NoticeCopiedFile = "Arquivo copiado",
            NoticeCopiedFiles = "{n} arquivos copiados",
            NoticeCpu = "CPU {p}%",
            NoticeMemory = "Memória {p}%",
            NoticeEventSoon = "Em {m} min",
            NoticeEventNow = "Agora",
            NoticeMicInUse = "Microfone em uso",
            NoticeCameraInUse = "Câmera em uso",
            NotifySection = "Avisos da ilha",
            NotifyPower = "Carregamento e bateria",
            NotifyBluetooth = "Dispositivos Bluetooth",
            NotifyNetwork = "Conexão com a internet",
            NotifyFocus = "Sessões de foco",
            NotifyClipboard = "Cópias na área de transferência",
            NotifyLoad = "CPU e memória altas",
            NotifyPrivacy = "Microfone e câmera em uso",
            NotifyToasts = "Notificações do Windows (lê todas as notificações)",
            HideToastBanners = "Notificações do Windows só na barra (ocultar pop-ups do Windows)",

            CrashReports = "Enviar relatórios de falha (erro, versão do app e do Windows, dados básicos do aparelho — sem arquivos, títulos ou perguntas)",
            CheckUpdates = "Procurar atualizações uma vez por dia",
            UpdateAvailable = "Atualização disponível — clique para instalar",
            UpdateMenu = "Atualizar agora",
            AllNotifications = "Todas as notificações",
            ResetsAt = "renova às {}",
            UsageLimit = "Limite de uso do {a}",
            UsageHigh = "Uso do {a} {p}%",
            AgentStopped = "{a} parou",
            StopLogin = "entre novamente",
            StopBilling = "verifique seu plano",
            StopBusy = "servidores ocupados, tente de novo",
            StopError = "interrompido por um erro",
            MuteChimeFullscreen = "Silenciar o som em tela cheia (jogos, vídeos)",
            UpdateFailed = "Falha na atualização — clique para baixar",
            ConnectAgents = "Conectar Claude Code / Codex (trabalhando · aguardando · pronto na barra)",
            ConnectAgentsCard = "Veja aqui o que Claude Code / Codex estão fazendo — clique para conectar",
            CalendarIcs = "Agenda (link ICS)",
            CalendarIcsHint = "Cole o endereço iCal secreto da sua agenda — deixe vazio para desativar",
            DropCommand = "Comando ao soltar",
            AdvancedSection = "Avançado",
            DropCommandHint = "Arquivos soltos na barra são passados a este comando (ex.: \"pythonw.exe\" \"C:\\send.py\"). Vazio = padrão",
            DropToAttach = "Anexar ao prompt",
            ReplaceTimerAsk = "Substituir? ↵ / Esc",
            StyleSection = "Aparência",
            StyleGlass = "Borda de vidro (barra escura)",
            Pomodoro = "Pomodoro",
            Stopwatch = "Cronômetro",
            Focus = "Foco",
            Break = "Pausa",
            Minutes = "{0} min",
            PomodoroMinutes = "Pomodoro (foco / pausa / pausa longa, min)",
            QuickTimersLabel = "Temporizadores rápidos no menu do botão direito (min, separados por vírgula)",
            NativeSearchBox = "Ocultar a caixa de pesquisa real (nativo)",
            AudioBars = "As barras seguem o som",
            Working = "trabalhando",
            NeedsAnswer = "aguardando",
            AgentDone = "concluído",
        },
        ["es"] = new LanguageStrings
        {
            Finishing = "Finalizando", Options = "Opciones de inicio", Settings = "Configuración",
            Quit = "Cerrar la barra", LaunchFail = "Error al iniciar: {}",
            NoSdk = "No se encontró Everything SDK (Everything64.dll)", EsOff = "Everything no se está ejecutando",
            EsFail = "Error en la búsqueda", NoResult = "Sin resultados", Done = "Listo", Fail = "Error",
            Prep = "Preparando", MinSec = "{m} min {s:02d} s", Sec = "{s} s",
            Lang = "Idioma", Auto = "Automático", Folder = "Carpeta de trabajo", FolderChange = "Cambiar",
            FolderHome = "Inicio", Files = "Búsqueda de archivos (Everything)",
            Session = new("Sesión", ["Nueva", "Reciente", "Elegir"]),
            Model = new("Modelo", ["Predet.", "Opus", "Sonnet", "Haiku", "Fable"]),
            Effort = new("Esfuerzo", ["Predet.", "Bajo", "Medio", "Alto", "Máx."]),
            Perm = new("Permisos", ["Omitir", "Auto", "Plan", "Preguntar"]),
            Rc = "Control remoto",
            Agent = "Agente",
            Dismiss = "Quitar",
            WebEngine = "Motor de búsqueda web",
            TabOrder = "Orden de Tab",
            WebSearch = "Búsqueda web",
            Timer = "Temporizador",
            // ---- System notices (09-30) ----
            NoticeCharging = "Cargando · {p} %",
            NoticeOnBattery = "Con batería · {p} %",
            NoticeBatteryLevel = "Batería {p} %",
            NoticeAboutMin = "aprox. {m} min",
            NoticeAboutHourMin = "aprox. {h} h {m} min",
            NoticeConnected = "{} · Conectado",
            NoticeDisconnected = "{} · Desconectado",
            NoticeOffline = "Sin internet",
            NoticeOnline = "Conectado de nuevo",
            NoticeFocus = "Sesión de concentración",
            NoticeCopied = "Copiado · {}",
            NoticeCopiedImage = "Imagen copiada",
            NoticeCopiedFile = "Archivo copiado",
            NoticeCopiedFiles = "{n} archivos copiados",
            NoticeCpu = "CPU {p} %",
            NoticeMemory = "Memoria {p} %",
            NoticeEventSoon = "En {m} min",
            NoticeEventNow = "Ahora",
            NoticeMicInUse = "Micrófono en uso",
            NoticeCameraInUse = "Cámara en uso",
            NotifySection = "Avisos de la isla",
            NotifyPower = "Carga y batería",
            NotifyBluetooth = "Dispositivos Bluetooth",
            NotifyNetwork = "Conexión a internet",
            NotifyFocus = "Sesiones de concentración",
            NotifyClipboard = "Copias al portapapeles",
            NotifyLoad = "CPU y memoria altas",
            NotifyPrivacy = "Micrófono y cámara en uso",
            NotifyToasts = "Notificaciones de Windows (lee todas las notificaciones)",
            HideToastBanners = "Notificaciones de Windows solo en la barra (ocultar ventanas de Windows)",

            CrashReports = "Enviar informes de errores (error, versión de la app y de Windows, datos básicos del equipo — sin archivos, títulos ni preguntas)",
            CheckUpdates = "Buscar actualizaciones una vez al día",
            UpdateAvailable = "Actualización disponible — haz clic para instalarla",
            UpdateMenu = "Actualizar ahora",
            AllNotifications = "Todas las notificaciones",
            ResetsAt = "se restablece a las {}",
            UsageLimit = "Límite de uso de {a}",
            UsageHigh = "Uso de {a} {p} %",
            AgentStopped = "{a} se detuvo",
            StopLogin = "vuelve a iniciar sesión",
            StopBilling = "revisa tu plan",
            StopBusy = "servidores ocupados, inténtalo de nuevo",
            StopError = "detenido por un error",
            MuteChimeFullscreen = "Silenciar el sonido en pantalla completa (juegos, vídeos)",
            UpdateFailed = "La actualización falló — haz clic para descargarla",
            ConnectAgents = "Conectar Claude Code / Codex (trabajando · esperando · listo en la barra)",
            ConnectAgentsCard = "Ve aquí lo que hacen Claude Code / Codex — haz clic para conectar",
            CalendarIcs = "Calendario (enlace ICS)",
            CalendarIcsHint = "Pega la dirección iCal secreta de tu calendario — vacío para desactivar",
            DropCommand = "Comando al soltar",
            AdvancedSection = "Avanzado",
            DropCommandHint = "Los archivos soltados en la barra se pasan a este comando (p. ej. \"pythonw.exe\" \"C:\\send.py\"). Vacío = predeterminado",
            DropToAttach = "Adjuntar al prompt",
            ReplaceTimerAsk = "¿Reemplazar? ↵ / Esc",
            StyleSection = "Apariencia",
            StyleGlass = "Borde de cristal (barra oscura)",
            Pomodoro = "Pomodoro",
            Stopwatch = "Cronómetro",
            Focus = "Concentración",
            Break = "Descanso",
            Minutes = "{0} min",
            PomodoroMinutes = "Pomodoro (concentración / descanso / descanso largo, min)",
            QuickTimersLabel = "Temporizadores rápidos del menú contextual (min, separados por comas)",
            NativeSearchBox = "Ocultar el cuadro de búsqueda real (nativo)",
            AudioBars = "Las barras siguen el sonido",
            Working = "trabajando",
            NeedsAnswer = "esperando",
            AgentDone = "listo",
        },
    };
}

/// <summary>Language code and the language's name in itself.</summary>
public sealed record LanguageInfo(string Code, string NativeName);
